# Generated by Django 4.2.25 on 2025-12-08 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmisionInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'admision_inscripcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjecuformInscripcioninteresadoformacionejecutiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ejecuform_inscripcioninteresadoformacionejecutiva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjecuformInstructorformacionejecutiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ejecuform_instructorformacionejecutiva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjecuformInstructorformaejecutiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ejecuform_instructorformaejecutiva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostulaciondipInscripcionpostulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'postulaciondip_inscripcionpostulante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sga_administrativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name': 'Carrera SGA',
                'db_table': 'sga_carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaEmpleador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sga_empleador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sga_externo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sga_inscripcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaPerfilusuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sga_perfilusuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='', max_length=100)),
                ('apellido1', models.CharField(default='', max_length=50)),
                ('apellido2', models.CharField(default='', max_length=50)),
                ('cedula', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'sga_persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaPostulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sga_postulante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaPostulanteempleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sga_postulanteempleo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sga_profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatbotRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('campo_sga', models.CharField(help_text='Nombre exacto del campo en SgaPerfilusuario que valida este rol', max_length=50)),
                ('carreras', models.ManyToManyField(blank=True, db_constraint=False, to='chatbot.sgacarrera')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RagDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='rag_docs/', verbose_name='Archivo Físico')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre visible')),
                ('is_infinite', models.BooleanField(default=False, verbose_name='Vigencia Indefinida')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
                ('doc_id_pgpt', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID en PrivateGPT')),
                ('is_indexed', models.BooleanField(default=False, verbose_name='Indexado en IA')),
                ('roles_permitidos', models.ManyToManyField(blank=True, to='chatbot.chatbotrol', verbose_name='Roles permitidos')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Conocimiento',
                'verbose_name_plural': 'Documentos de Conocimiento',
                'db_table': 'chatbot_rag_documents',
            },
        ),
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Proceso')),
                ('business_context', models.TextField(default='Descripcion', verbose_name='Contexto del proceso')),
                ('process_type', models.CharField(choices=[('informativo', 'Informativo'), ('operativo', 'Operativo')], default='informativo', max_length=20, verbose_name='Tipo de Proceso')),
                ('source_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Fuente o referencia (opcional)')),
                ('closed_message', models.TextField(blank=True, null=True, verbose_name='Mensaje Personalizado (No Disponible)')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('is_infinite', models.BooleanField(default=False, verbose_name='Es Indefinido')),
                ('active_message', models.TextField(verbose_name='Mensaje cuando está Activo')),
                ('need_documentation', models.BooleanField(default=False, verbose_name='Requiere Documentación')),
                ('roles_permitidos', models.ManyToManyField(blank=True, to='chatbot.chatbotrol', verbose_name='Roles Permitidos')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso de Negocio',
                'verbose_name_plural': 'Procesos de Negocio',
                'db_table': 'chatbot_business_processes',
                'managed': True,
            },
        ),
    ]
