# Generated by Django 4.2.25 on 2025-12-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosgradoInscripcionaspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'posgrado_inscripcionaspirante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SagestCapinstructoripec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sagest_capinstructoripec',
                'managed': False,
            },
        ),
    ]
