# Generated by Django 4.2.25 on 2025-11-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_businessprocess_delete_academiaactivatematter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='roles',
            field=models.JSONField(default=list, verbose_name='Roles Permitidos'),
        ),
    ]
