# Generated by Django 4.2.25 on 2025-12-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_posgradoinscripcionaspirante_sagestcapinstructoripec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EjecuformInscripcioninteresadoformacionejecutiva',
        ),
        migrations.DeleteModel(
            name='EjecuformInstructorformacionejecutiva',
        ),
        migrations.DeleteModel(
            name='EjecuformInstructorformaejecutiva',
        ),
        migrations.DeleteModel(
            name='PosgradoInscripcionaspirante',
        ),
    ]
