# Generated by Django 4.2.25 on 2025-12-09 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0003_delete_ejecuforminscripcioninteresadoformacionejecutiva_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessprocess',
            options={'managed': True, 'verbose_name': 'Proceso de Negocio'},
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='active_message',
            field=models.TextField(verbose_name='Mensaje Activo'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='closed_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje No Disponible'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='source_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Fuente'),
        ),
        migrations.CreateModel(
            name='BusinessProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Tipo')),
                ('codigo', models.CharField(help_text='Uso interno (ej: OPERATIVO)', max_length=50, unique=True)),
                ('requiere_documentacion_por_defecto', models.BooleanField(default=False, verbose_name='¿Suele requerir docs?')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Proceso',
                'verbose_name_plural': 'Tipos de Procesos',
                'db_table': 'chatbot_process_types',
            },
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='process_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='chatbot.businessprocesstype', verbose_name='Tipo de Proceso'),
        ),
    ]
