# Generated by Django 4.2.25 on 2025-11-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_businessprocess_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprocess',
            name='closed_message',
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='need_documentation',
            field=models.BooleanField(default=False, verbose_name='Requiere Documentación'),
        ),
    ]
