# Generated by Django 4.2.25 on 2025-12-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_businessprocess_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprocesstype',
            name='codigo',
        ),
    ]
