# Generated by Django 4.2.25 on 2025-11-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_businessprocess_closed_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprocess',
            name='trigger_function',
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='business_context',
            field=models.TextField(default='Descripcion', verbose_name='Contexto del proceso'),
        ),
    ]
