# Generated by Django 4.2.25 on 2025-11-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_businessprocess_trigger_function_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='process_type',
            field=models.CharField(choices=[('informativo', 'Informativo'), ('operativo', 'Operativo')], default='informativo', max_length=20, verbose_name='Tipo de Proceso'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='source_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Fuente o referencia (opcional)'),
        ),
    ]
