# Generated by Django 4.2.25 on 2025-12-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_businessprocesstype_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgaMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('retiradomatricula', models.BooleanField(default=False)),
                ('estado_matricula', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'sga_matricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sga_nivel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'sga_periodo',
                'managed': False,
            },
        ),
    ]
