# Generated by Django 4.2.25 on 2025-12-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_sgamatricula_sganivel_sgaperiodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalconCategoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'balcon_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalconCategoriaCoordinaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'balcon_categoria_coordinaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalconProceso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'balcon_proceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GobeSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'gobe_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaCoordinacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sga_coordinacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sga_materia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaRecordAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('asistencia', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('aprobada', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sga_recordacademico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelado', models.BooleanField(default=False)),
                ('fecha_vence', models.DateField(null=True)),
            ],
            options={
                'db_table': 'sga_rubro',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='sgacarrera',
            options={'managed': False},
        ),
    ]
