# Generated by Django 4.2.25 on 2025-11-30 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0006_businessprocess_process_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='rag_docs/', verbose_name='Archivo Físico')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre visible')),
                ('roles', models.JSONField(default=list, verbose_name='Roles permitidos')),
                ('is_infinite', models.BooleanField(default=False, verbose_name='Vigencia Indefinida')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
                ('doc_id_pgpt', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID en PrivateGPT')),
                ('is_indexed', models.BooleanField(default=False, verbose_name='Indexado en IA')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Conocimiento',
                'verbose_name_plural': 'Documentos de Conocimiento',
                'db_table': 'chatbot_rag_documents',
            },
        ),
    ]
