# Generated by Django 4.2.25 on 2025-12-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_balconcategoria_balconcategoriacoordinaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgaCoordinacionCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sga_coordinacion_carrera',
                'managed': False,
            },
        ),
    ]
