# Generated by Django 4.2.25 on 2025-12-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_sgacoordinacioncarrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalconTipo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'balcon_tipo',
                'managed': False,
            },
        ),
    ]
