# Generated by Django 4.2.25 on 2025-12-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_balcontipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalconAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'balcon_agente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalconProcesoservicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('tiempomaximo', models.IntegerField()),
                ('tiempominimo', models.IntegerField()),
                ('minutos', models.IntegerField()),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'balcon_procesoservicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalconRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'balcon_requisito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalconRequisitosconfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('obligatorio', models.BooleanField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'balcon_requisitosconfiguracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalconRequisitossolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('archivo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'balcon_requisitossolicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalconServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'balcon_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalconServiciodepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('reasignar', models.BooleanField()),
            ],
            options={
                'db_table': 'balcon_serviciodepartamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalconServicioOpcsistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'balcon_servicio_opcsistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalconSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('archivo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField()),
                ('externo', models.BooleanField()),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('tiempoespera', models.IntegerField(blank=True, null=True)),
                ('tiempoesperareal', models.IntegerField(blank=True, null=True)),
                ('solicitud_devuelta', models.BooleanField()),
                ('fecha_expiracion_solicitud', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'balcon_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SagestCarreradepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sagest_carreradepartamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SagestOpcionsistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sagest_opcionsistema',
                'managed': False,
            },
        ),
    ]
