# Generated by Django 4.2.25 on 2025-12-31 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_rename_business_context_to_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='servicio_origen',
            field=models.ForeignKey(blank=True, help_text='Si se selecciona, el nombre y descripción se copiarán de este servicio.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.balconservicio', verbose_name='Servicio Vinculado (Legacy)'),
        ),
    ]
