# Generated by Django 4.2.25 on 2025-12-31 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_businessprocess_servicio_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='proceso_origen',
            field=models.ForeignKey(blank=True, help_text='Proceso del sistema legacy al que está vinculado este proceso de negocio.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.balconproceso', verbose_name='Proceso Vinculado (Legacy)'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='servicio_origen',
            field=models.ForeignKey(blank=True, help_text='Servicio del proceso seleccionado. Se llena automáticamente al seleccionar un servicio del proceso.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.balconservicio', verbose_name='Servicio Vinculado (Legacy)'),
        ),
    ]
