# Generated by Django 4.2.25 on 2025-12-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_businessprocess_proceso_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='tipo_audiencia',
            field=models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo'), ('ambos', 'Ambos')], default='ambos', help_text='Indica si el proceso es para usuarios internos, externos o ambos.', max_length=20, verbose_name='Tipo de Audiencia'),
        ),
    ]
