# Generated by Django 4.2.25 on 2025-12-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_businessprocess_tipo_audiencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprocess',
            name='need_documentation',
        ),
    ]
