# Generated by Django 4.2.25 on 2026-01-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_remove_businessprocess_need_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgaAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre Asignatura')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sga_asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Aula')),
            ],
            options={
                'db_table': 'sga_aula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Día')),
            ],
            options={
                'db_table': 'sga_dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('fin', models.TimeField(verbose_name='Hora Fin')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sga_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre Institución')),
            ],
            options={
                'db_table': 'sga_institucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaMateriaasignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sga_materiaasignada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaParticipacionproyectovinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.IntegerField(default=0)),
                ('aprobado', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sga_participacionproyectovinculacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaPracticaspreprofesionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerohora', models.IntegerField(default=0)),
                ('fechainicio', models.DateField(null=True)),
                ('validada', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sga_practicaspreprofesionales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaProyectovinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre Proyecto')),
            ],
            options={
                'db_table': 'sga_proyectovinculacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaSustentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, max_length=1000, null=True)),
                ('fechahora', models.DateTimeField(blank=True, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sga_sustentacion',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='sganivel',
            options={'managed': False, 'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='sgaperiodo',
            options={'managed': False, 'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
    ]
