# Generated by Django 4.2.25 on 2026-01-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_sgaasignatura_sgaaula_sgadia_sgahorario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sganivel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sgaperiodo',
            options={'managed': False},
        ),
    ]
