# Generated by Django 4.2.25 on 2026-01-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_alter_sganivel_options_alter_sgaperiodo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'sga_grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaMalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacreacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sga_malla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaModalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'sga_modalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaNivelmalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'sga_nivelmalla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'sga_sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'sga_sesion',
                'managed': False,
            },
        ),
    ]
