# Generated by Django 4.2.25 on 2026-01-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_sgagrupo_sgamalla_sgamodalidad_sganivelmalla_sgasede_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgaDetallemodeloevaluativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('notamaxima', models.FloatField(blank=True, null=True)),
                ('notaminima', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sga_detallemodeloevaluativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaDetallerecordacademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sga_detallerecordacademico',
                'managed': False,
            },
        ),
    ]
