# Generated by Django 4.2.25 on 2026-01-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_sgadetallemodeloevaluativo_sgadetallerecordacademico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SgaDetallemodeloevaluativo',
        ),
        migrations.DeleteModel(
            name='SgaDetallerecordacademico',
        ),
    ]
