# Generated by Django 4.2.25 on 2026-01-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_delete_sgadetallemodeloevaluativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgaTiporubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
                ('activo', models.BooleanField()),
                ('status', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('rubro_matricula', models.BooleanField(blank=True, null=True)),
                ('rubro_arancel', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sga_tiporubro',
                'managed': False,
            },
        ),
    ]
