# Generated by Django 4.2.25 on 2026-01-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_sgatiporubro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SagestRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('nombre', models.CharField(max_length=300)),
                ('cuota', models.IntegerField(default=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fechavence', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('cancelado', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sagest_rubro',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SgaRubro',
        ),
    ]
