# Generated by Django 4.2.25 on 2026-01-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0024_academiaactasolicitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(help_text='Esto se vectoriza para buscar similitud')),
                ('respuesta', models.TextField(help_text='Esto se devuelve tal cual si hay coincidencia')),
                ('activo', models.BooleanField(default=True)),
                ('doc_id_pgpt', models.CharField(blank=True, help_text='ID interno en PrivateGPT', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'managed': True,
            },
        ),
    ]
