"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Cargar variables de entorno desde .env
load_dotenv()

# Fix para Windows: Excluir módulos congelados del autoreload
# Esto evita el error OSError: [WinError 123] con <frozen importlib._bootstrap>
if sys.platform == 'win32':
    import django.utils.autoreload
    from pathlib import Path as PathLib
    
    original_iter_all_python_module_files = django.utils.autoreload.iter_all_python_module_files
    
    def patched_iter_all_python_module_files():
        for module_file in original_iter_all_python_module_files():
            try:
                # Intentar convertir a Path y verificar si existe
                path = PathLib(module_file)
                if path.exists():
                    yield module_file
            except (OSError, ValueError, TypeError):
                # Si hay error al verificar, simplemente omitir este archivo
                continue
    
    django.utils.autoreload.iter_all_python_module_files = patched_iter_all_python_module_files

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# RAG Configuration (FAISS)
FAISS_INDEX_PATH = BASE_DIR / "faiss_index"
DOCUMENTOS_DIR = BASE_DIR / "documentos_unemi"

# RAG Document Processing Configuration
RAG_CHUNK_SIZE = int(os.getenv('RAG_CHUNK_SIZE', '1024'))
RAG_CHUNK_OVERLAP = int(os.getenv('RAG_CHUNK_OVERLAP', '512'))
RAG_MAX_FILE_SIZE_MB = int(os.getenv('RAG_MAX_FILE_SIZE_MB', '50'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h#)k9p4%w%rd)@22xj2(fm2&-*%nz05b!z2-jiqk6t@=9pw5+8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS settings para permitir requests del frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite dev server
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Ollama Configuration
OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL', 'http://localhost:11434')
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'qwen2.5:3b-instruct-q4_K_M')

# Ollama Advanced Parameters (optimizados para extracción de JSON en CPU)
OLLAMA_NUM_PREDICT = int(os.getenv('OLLAMA_NUM_PREDICT', '512'))  # Limita tokens para velocidad
OLLAMA_REPEAT_PENALTY = float(os.getenv('OLLAMA_REPEAT_PENALTY', '1.1'))  # Evita bucles
OLLAMA_TOP_P = float(os.getenv('OLLAMA_TOP_P', '0.9'))  # Control de muestreo
OLLAMA_TOP_K = int(os.getenv('OLLAMA_TOP_K', '40'))  # Control de muestreo
OLLAMA_TEMPERATURE = float(os.getenv('OLLAMA_TEMPERATURE', '0.0'))  # Máxima precisión (cero creatividad)
OLLAMA_NUM_CTX = int(os.getenv('OLLAMA_NUM_CTX', '8192'))  # Ventana de contexto
OLLAMA_FORMAT = os.getenv('OLLAMA_FORMAT', 'json')  # Fuerza estructura JSON
OLLAMA_NUM_THREAD = int(os.getenv('OLLAMA_NUM_THREAD', '6'))  # Threads CPU (8 cores - 2 para sistema)
